spring:
    datasource:
        url: jdbc:h2:tcp://localhost/~/jpashop #;MVCC=TRUE
        username: sa
        password:
        driver-class-name: org.h2.Driver

    jpa:
        hibernate:
            ddl-auto: create #none
        properties:
            hibernate:
#                show_sql: true # System.out.print 로 찍히는 로그
                format_sql: true

logging:
    level:
        org.hibernate.SQL: debug # Logger 로 찍히는 로그
#        org.hibernate.type: trace # spring-boot-data-source-decorator 로 대체